trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(Major).$(Minor)$(Rev:.r)


steps:
- task: PowerShell@2
  displayName: 'Set extension version'
  inputs:
    targetType: 'inline'
    script: |
      $manifest = Get-Content $(ManifestPath) | ConvertFrom-Json
      $manifest.version = $(Build.BuildNumber)
      $manifest | ConvertTo-Json | Set-Content $(ManifestPath)

- task: Npm@1
  displayName: 'NPM install'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'NPM build'
  inputs:
    command: 'custom'
    customCommand: 'run build'


- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: 'dimati93.d93-release-notes-$(Build.BuildNumber).vsix'
    artifact: 'extension'
    publishLocation: 'pipeline'